"""可替换的号码评分与动态结构评分接口。"""

from dlt_number_analysis.scoring.number_scorers import (
    NUMBER_SCORER_VERSION,
    RECENCY_WINDOWS,
    BoundNumberScorer,
    NumberArea,
    NumberScorer,
    ScorerSpec,
    build_number_scorer,
    cumulative_frequency_score,
    hot_cold_blend_score,
    recency_weighted_frequency_score,
    uniform_score,
)
from dlt_number_analysis.scoring.structure import (
    DEFAULT_STRUCTURE_WEIGHTS,
    HistoricalStructureProfile,
    StructureComponentScore,
    StructureFeatureDefinition,
    StructureScore,
    TicketStructureFeatures,
    compute_ticket_structure,
    compute_ticket_structures_batch,
    fit_structure_profile,
    score_ticket_structure,
)

__all__ = [
    "DEFAULT_STRUCTURE_WEIGHTS",
    "NUMBER_SCORER_VERSION",
    "RECENCY_WINDOWS",
    "BoundNumberScorer",
    "HistoricalStructureProfile",
    "NumberArea",
    "NumberScorer",
    "ScorerSpec",
    "StructureComponentScore",
    "StructureFeatureDefinition",
    "StructureScore",
    "TicketStructureFeatures",
    "build_number_scorer",
    "compute_ticket_structure",
    "compute_ticket_structures_batch",
    "cumulative_frequency_score",
    "fit_structure_profile",
    "hot_cold_blend_score",
    "recency_weighted_frequency_score",
    "score_ticket_structure",
    "uniform_score",
]
