"""候选票池生成、评分明细持久化与五注 Portfolio 优化。"""

from dlt_number_analysis.portfolio.bank import (
    BankCacheKey,
    BankTicket,
    FeasiblePortfolioBank,
    FeasiblePortfolioEntry,
    FeasiblePortfolioSubset,
    PortfolioBankScoringResult,
    build_feasible_portfolio_bank,
    build_stable_portfolio_subset,
    candidate_numbers_hash,
    portfolio_constraints_signature,
    sample_constraint_matched_portfolio,
    score_portfolio_bank,
)
from dlt_number_analysis.portfolio.candidate_pool import (
    generate_candidate_pool,
    load_candidate_score_details,
    rescore_candidate_pool,
    rescore_candidate_pool_with_vectors,
    write_candidate_score_details,
)
from dlt_number_analysis.portfolio.models import (
    CandidatePool,
    CandidateTicketScore,
    PortfolioConstraints,
    PortfolioScoreBreakdown,
    PortfolioSelection,
    PortfolioTicket,
)
from dlt_number_analysis.portfolio.optimizer import (
    PortfolioOptimizationError,
    optimize_portfolio,
)
from dlt_number_analysis.portfolio.vectorized_scoring import (
    CandidateArrayBundle,
    CandidateScoreView,
    FeasiblePortfolioIndexBank,
    PortfolioScoreArrays,
    PortfolioScoringMethod,
    VectorizedPortfolioBankScoringResult,
    build_candidate_score_view,
    candidate_pool_to_array_bundle,
    candidate_score_view_from_arrays,
    feasible_portfolio_bank_to_index_bank,
    score_portfolio_bank_vectorized,
)

__all__ = [
    "BankCacheKey",
    "BankTicket",
    "CandidateArrayBundle",
    "CandidatePool",
    "CandidateScoreView",
    "CandidateTicketScore",
    "FeasiblePortfolioBank",
    "FeasiblePortfolioEntry",
    "FeasiblePortfolioIndexBank",
    "FeasiblePortfolioSubset",
    "PortfolioBankScoringResult",
    "PortfolioConstraints",
    "PortfolioOptimizationError",
    "PortfolioScoreArrays",
    "PortfolioScoreBreakdown",
    "PortfolioScoringMethod",
    "PortfolioSelection",
    "PortfolioTicket",
    "VectorizedPortfolioBankScoringResult",
    "build_candidate_score_view",
    "build_feasible_portfolio_bank",
    "build_stable_portfolio_subset",
    "candidate_numbers_hash",
    "candidate_pool_to_array_bundle",
    "candidate_score_view_from_arrays",
    "feasible_portfolio_bank_to_index_bank",
    "generate_candidate_pool",
    "load_candidate_score_details",
    "optimize_portfolio",
    "portfolio_constraints_signature",
    "rescore_candidate_pool",
    "rescore_candidate_pool_with_vectors",
    "sample_constraint_matched_portfolio",
    "score_portfolio_bank",
    "score_portfolio_bank_vectorized",
    "write_candidate_score_details",
]
